name: run-app

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-app:
    runs-on: ubuntu-latest
    env:
      DISCORD_USERID: ${{ secrets.DISCORD_USERID }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master
      -
        name: Cache version.json
        uses: actions/cache@v2
        with:
          path: ./version
          key: ${{ runner.os }}-rogph5updatechker-${{ github.run_number }}
          restore-keys: ${{ runner.os }}-rogph5updatechker-
      -
        name: Install pre-requisites
        run : |
          pip3 install -r requirements.txt
      -
        name: Check cache
        continue-on-error: true
        run : |
          mkdir -p version
          ls version
          cat version/version.json
      -
        name: Execute app
        run : |
          python3 main.py