name: run-app

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-app:
    runs-on: ubuntu-latest
    env:
      DISCORD_USERID: ${{ secrets.DISCORD_USERID }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master
      -
        name: Cache version.json
        uses: actions/cache@v2
        with:
          path: ~/app-cache
          key: ${{ runner.os }}-rogph5updatechker
      -
        name: Move cache to repo directory
        continue-on-error: true
        run: |
          cp ~/app-cache/version.json ./
      -
        name: Install pre-requisites
        run : |
          pip3 install -r requirements.txt
      -
        name: Execute app
        run : |
          python3 main.py
      -
        name: Move version.json to cache directory
        run: |
          mkdir -p ~/app-cache/ && cp ./version.json ~/app-cache/
          rm version.json