name: run-app

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISCORD_USERID: ${{ secrets.DISCORD_USERID }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master
      -
        name: Cache version.json
        uses: actions/cache@v2
        with:
          path: /tmp/.app-cache
          key: ${{ runner.os }}-rogph5updatechker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-rogph5updatechker-
      -
        name: Move cache to repo directory
        continue-on-error: true
        run: |
          cp /tmp/.app-cache/version.json ./
      -
        name: Execute app
        run : |
          pip3 install -r requirements.txt
          python3 main.py
      -
        name: Move version.json to cache directory
        run: |
          mkdir -p /tmp/.app-cache/ && cp ./version.json /tmp/.app-cache/
          rm version.json